### PR TITLE
Missing -I for gamerapy

### PR DESCRIPTION
**Pull request by cdeil**
I'm getting this error trying to build gamerapy (just `make` works)

```
$ make gamerapy
cd python;\
    swig -python -c++ -nosafecstrings  -outdir ../lib -o _gamerapy.cc gamerapy.i;\
    python setup.py build_ext --build-lib ../lib;\
    cd ..;\

running build_ext
building '_gamerapy' extension
/usr/bin/clang -Wno-unused-result -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c _gamerapy.cc -o build/temp.macosx-10.11-x86_64-3.4/_gamerapy.o -std=c++11
In file included from _gamerapy.cc:3143:
./../include/Radiation.h:9:10: fatal error: 'gsl/gsl_sf_bessel.h' file not found
#include <gsl/gsl_sf_bessel.h>
         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
$ pkg-config --cflags gsl
-I/opt/local/include 
```

### CODE REVIEW

**Comment by JoachimHahn** [comment]
Thanks!

I committed an update to the python/setup.py file that now includes the headers. For my system (and I think linux systems in general), the headers are in /usr/include/gsl. Can you check if this works for Mac too? 

Cheers Joachim

**Comment by cdeil** [comment]
Your fix does not work.

You shouldn't hard-code header and libs locations.

The most common solution is to use `pkg-config` to locate headers and libraries, this works on most Linux / Mac machines (if it doesn't, the system can be considered broken and many other software builds won't work either).

For me the gsl headers are in `/opt/local/include` (but don't hard-code that as an option, please):

```
$ pkg-config --cflags gsl
-I/opt/local/include 
```

**Comment by JoachimHahn** [comment]
You're right!
I committed a new version of the Makefile (and removed the hard-coded stuff in the setup.py file) where I give the flags from  gsl-config --cflags to the swig command. Works for me!

**Comment by cdeil** [comment]
Still doesn't work for me:

```
$ make gamerapy
cd python;\
    swig -python -c++ -nosafecstrings -I/opt/local/include -outdir ../lib -o _gamerapy.cc gamerapy.i;\
    python setup.py build_ext --build-lib ../lib;\
    cd ..;\

running build_ext
building '_gamerapy' extension
creating build
creating build/temp.macosx-10.11-x86_64-3.4
creating build/src
/usr/bin/clang -Wno-unused-result -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -I../include -I/opt/local/Library/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c _gamerapy.cc -o build/temp.macosx-10.11-x86_64-3.4/_gamerapy.o -std=c++11
In file included from _gamerapy.cc:3143:
./../include/Radiation.h:9:10: fatal error: 'gsl/gsl_sf_bessel.h' file not found
#include <gsl/gsl_sf_bessel.h>
         ^
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
```

You need to add the LIBS and CFLAGS in setup.py.

I don't have much experience with this ... if I had to do it, I'd bundle a copy of this helper file in your repo (https://github.com/matze/pkgconfig/blob/master/pkgconfig/pkgconfig.py) and then in setup.py import it and call `pkgconfig.libs('gsl')` and `pkgconfig.cflags('gsl')`, passing the info into the `Extension` declaration.

There might be other ways to pass the info on to setuptools.

@JoachimHahn – Do you want to try this or should I make a pull request with this fix?

**Comment by cdeil** [comment]
You could always rewrite `GAMERA` using Python / Numpy / Scipy and all these build / install / C++ issues would be gone. :smirk_cat:

**Comment by JoachimHahn** [comment]
Then there would be other problems, as always :D and C++ users couldn't use it ;)

**Comment by JoachimHahn** [comment]
OK, I give the $(GSLCFLAGS) now to the setup.py. Does it work now on your system?

**Comment by cdeil** [comment]
No, it's not possible to pass GSLCFLAGS from the Makefile to setup.py like this, that doesn't work:
https://github.com/JoachimHahn/GAMERA/commit/0e131fa4f8e17efe3f2dc9a02baf73036094e8cb#diff-8cf6167d58ce775a08acafcfe6f40966R7

You can try the solution I mentioned before yourself by trying to get the gsl cflags in setup.py and just add a print statement to see if it works.

**Comment by JoachimHahn** [comment]
This last change broke it for me on linux.
I implemented a fix to python/setup.py that should work for both platforms, I hope.

**Comment by cdeil** [comment]
Time for testing on travis-ci!

(it'll automatically run on every pull request and warn you not to hit the merge button if tests fail)

**Pull request merged**
